version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  adminer:
    links:
      - postgres:postgres
    container_name: adminer
    image: adminer
    ports:
      - '8081:8080'
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
